version = 1

exclude_patterns = [
  ".idea/",
  "out/"
]

[[analyzers]]
name = "java"
enabled = true

  [analyzers.meta]
  runtime_version = "17"

[[transformers]]
name = "google-java-format"
enabled = true